#!/bin/bash
# File generated by precompile.c
case "$1" in
"100")
  echo "0xff6fc88c"
  ;;
"99")
  echo "0xff6fc88c"
  ;;
"98")
  echo "0xff6fc88c"
  ;;
"97")
  echo "0xff6fc88c"
  ;;
"96")
  echo "0xff6fc88c"
  ;;
"95")
  echo "0xff6fc88c"
  ;;
"94")
  echo "0xff6fc88c"
  ;;
"93")
  echo "0xff6fc88c"
  ;;
"92")
  echo "0xff6fc88c"
  ;;
"91")
  echo "0xff6fc88c"
  ;;
"90")
  echo "0xff6fc88c"
  ;;
"89")
  echo "0xff6fc88c"
  ;;
"88")
  echo "0xff6fc88c"
  ;;
"87")
  echo "0xff6fc88c"
  ;;
"86")
  echo "0xff6fc88c"
  ;;
"85")
  echo "0xff6fc88c"
  ;;
"84")
  echo "0xff6fc88c"
  ;;
"83")
  echo "0xff6fc88c"
  ;;
"82")
  echo "0xff6fc88c"
  ;;
"81")
  echo "0xff6fc88c"
  ;;
"80")
  echo "0xff6fc88c"
  ;;
"79")
  echo "0xff6fc88c"
  ;;
"78")
  echo "0xff6fc88c"
  ;;
"77")
  echo "0xff6fc88c"
  ;;
"76")
  echo "0xff6fc88c"
  ;;
"75")
  echo "0xff6fc88c"
  ;;
"74")
  echo "0xff6fc88c"
  ;;
"73")
  echo "0xff6fc88c"
  ;;
"72")
  echo "0xff6fc88c"
  ;;
"71")
  echo "0xff6fc88c"
  ;;
"70")
  echo "0xff6fc88c"
  ;;
"69")
  echo "0xff6fc88c"
  ;;
"68")
  echo "0xff6fc88c"
  ;;
"67")
  echo "0xff6fc88c"
  ;;
"66")
  echo "0xff6fc78c"
  ;;
"65")
  echo "0xff6fc78c"
  ;;
"64")
  echo "0xff6fc78c"
  ;;
"63")
  echo "0xff6fc78b"
  ;;
"62")
  echo "0xff6fc78b"
  ;;
"61")
  echo "0xff6fc68b"
  ;;
"60")
  echo "0xff6fc68b"
  ;;
"59")
  echo "0xff6fc68b"
  ;;
"58")
  echo "0xff70c68b"
  ;;
"57")
  echo "0xff70c58a"
  ;;
"56")
  echo "0xff70c58a"
  ;;
"55")
  echo "0xff70c48a"
  ;;
"54")
  echo "0xff70c489"
  ;;
"53")
  echo "0xff70c389"
  ;;
"52")
  echo "0xff70c389"
  ;;
"51")
  echo "0xff71c288"
  ;;
"50")
  echo "0xff71c288"
  ;;
"49")
  echo "0xff71c188"
  ;;
"48")
  echo "0xff71c087"
  ;;
"47")
  echo "0xff72bf86"
  ;;
"46")
  echo "0xff72bf86"
  ;;
"45")
  echo "0xff72be85"
  ;;
"44")
  echo "0xff73bd85"
  ;;
"43")
  echo "0xff73bc84"
  ;;
"42")
  echo "0xff74ba83"
  ;;
"41")
  echo "0xff74b982"
  ;;
"40")
  echo "0xff74b881"
  ;;
"39")
  echo "0xff75b680"
  ;;
"38")
  echo "0xff75b57f"
  ;;
"37")
  echo "0xff76b37e"
  ;;
"36")
  echo "0xff77b27d"
  ;;
"35")
  echo "0xff77b07c"
  ;;
"34")
  echo "0xff78ae7b"
  ;;
"33")
  echo "0xff79ac79"
  ;;
"32")
  echo "0xff79aa78"
  ;;
"31")
  echo "0xff7aa776"
  ;;
"30")
  echo "0xff7ba575"
  ;;
"29")
  echo "0xff7ca273"
  ;;
"28")
  echo "0xff7da071"
  ;;
"27")
  echo "0xff7e9d6f"
  ;;
"26")
  echo "0xff7f9a6d"
  ;;
"25")
  echo "0xff80976b"
  ;;
"24")
  echo "0xff819369"
  ;;
"23")
  echo "0xff839067"
  ;;
"22")
  echo "0xff848c64"
  ;;
"21")
  echo "0xff858862"
  ;;
"20")
  echo "0xff87845f"
  ;;
"19")
  echo "0xff887f5c"
  ;;
"18")
  echo "0xff8a7b59"
  ;;
"17")
  echo "0xff8c7656"
  ;;
"16")
  echo "0xff8e7152"
  ;;
"15")
  echo "0xff8f6c4f"
  ;;
"14")
  echo "0xff91664b"
  ;;
"13")
  echo "0xff936147"
  ;;
"12")
  echo "0xff965a43"
  ;;
"11")
  echo "0xff98543f"
  ;;
"10")
  echo "0xff9a4e3b"
  ;;
"9")
  echo "0xff9d4736"
  ;;
"8")
  echo "0xff9f3f31"
  ;;
"7")
  echo "0xffa2382c"
  ;;
"6")
  echo "0xffa53027"
  ;;
"5")
  echo "0xffa82822"
  ;;
"4")
  echo "0xffab1f1c"
  ;;
"3")
  echo "0xffae1616"
  ;;
"2")
  echo "0xffb10d10"
  ;;
"1")
  echo "0xffb5040a"
  ;;
*)
  echo "0xff000000"
  ;;
esac
